import Head from "next/head";
import { SWRConfig } from "swr";
import axiosClient from "@/api/axios-client";
import { EmptyLayout } from "@/components/layout";
import { AppPropsWithLayout } from "@/models/common";
import "../styles/globals.css";

function MyApp({ Component, pageProps }: AppPropsWithLayout) {
  const Layout = Component.Layout || EmptyLayout;
  return (
    <SWRConfig value={{ fetcher: (url) => axiosClient.get(url) }}>
      <Layout>
        <Head>
          <title>App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Component {...pageProps} />
      </Layout>
    </SWRConfig>
  );
}

export default MyApp;
